on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
        type: choice
        options:
          - info
          - warning
      tags:
        description: "Test scenario tags"
        required: false
        type: boolean

jobs:
  log-the-inputs2:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "AAAAAAAAAAAAAAAAAAA"
        env:
          LEVEL: ${{ inputs.logLevel }}
          TAGS: ${{ inputs.tags }}
